package model;

public enum TipoInforme {
    DESARROLLO_PRODUCTIVO,
    NIVEL_ACTIVIDAD_INDUSTRIAL,
    PROYECTOS_EN_EJECUCION,
    EVALUACION_TECNICA,
    CONSUMO_ELECTRICO,
    AVANCE_PROYECTOS,
    INFRAESTRUCTURA,
    GENERAL
}
